import { mkdir } from "node:fs/promises";
import path from "node:path";
import { collectArchitectureFacts } from "../analysis/architecture.js";
import { collectGitFacts } from "../git/facts.js";
import { loadChronicleStore } from "../store/eventsStore.js";
import { escapeHtml } from "../utils/html.js";
import { writeTextFileAtomic } from "../utils/atomic.js";
import { buildProjectBrainViewModel } from "./projectBrainViewModel.js";

const STATUS_LABELS = {
  completed: "shipped",
  in_progress: "in progress",
  planned: "planned",
  idea: "idea",
  blocked: "blocked",
  unknown: "unknown",
};

const EVENT_LABELS = {
  feature_added: "feature",
  bugfix: "bugfix",
  refactor: "refactor",
  dependency_changed: "dependency",
  version_bump: "version",
  decision: "decision",
  note: "note",
};

export async function renderProjectBrainToFile({ storePath, outputPath, rootDir = process.cwd() }) {
  const store = await loadChronicleStore(storePath);
  const [architecture, gitFacts] = await Promise.all([
    collectArchitectureFacts({ rootDir }),
    collectGitFacts({ rootDir }),
  ]);
  const html = renderProjectBrain(store.items, { storePath, architecture, gitFacts });
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeTextFileAtomic(outputPath, html, { backup: true });
  return { outputPath, itemCount: store.items.length };
}

export function renderProjectBrain(items, { storePath = "data/chronicle.json", architecture = null, gitFacts = null } = {}) {
  const model = buildProjectBrainViewModel(items);
  const dataJson = JSON.stringify(toClientData(model)).replace(/</g, "\\u003c");

  return `<!doctype html>
<html lang="en" data-theme="light" data-density="comfortable">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(model.projectName)} - Project Brain</title>
<style>${CSS}</style>
</head>
<body>
<div class="topbar">
  <div class="topbar-in">
    <div class="brand"><span class="dot"></span> Chronicle</div>
    <span class="proj">${escapeHtml(model.projectName)} · local brain</span>
    <div class="spacer"></div>
    <button class="searchbtn" id="openSearch" type="button" aria-label="Search project brain">
      ${icon("search")}<span>Search anything...</span><span class="kbd">⌘K</span>
    </button>
    <button class="queuebtn" id="openIntentQueue" type="button" aria-label="Open action intent queue">Intents <span id="intentCount">0</span></button>
  </div>
  <div class="tabbar"><div class="tabs" id="tabs">
    ${tabButton("overview", "Overview", "overview", true)}
    ${tabButton("features", `Features <span class="ct">${model.features.length}</span>`, "star")}
    ${tabButton("files", `Files <span class="ct">${model.files.length}</span>`, "folder")}
    ${tabButton("timeline", `Timeline <span class="ct">${model.events.length}</span>`, "clock")}
    ${tabButton("decisions", `Decisions <span class="ct">${model.decisions.length}</span>`, "scale")}
    ${tabButton("roadmap", `Roadmap <span class="ct">${model.roadmap.length}</span>`, "roadmap")}
  </div></div>
</div>

<main class="wrap">
  <section class="panel on" data-panel="overview">${overviewPanel(model, storePath, architecture, gitFacts)}</section>
  <section class="panel" data-panel="features">${featuresPanel(model)}</section>
  <section class="panel" data-panel="files">${filesPanel(model)}</section>
  <section class="panel" data-panel="timeline">${timelinePanel(model)}</section>
  <section class="panel" data-panel="decisions">${decisionsPanel(model)}</section>
  <section class="panel" data-panel="roadmap">${roadmapPanel(model)}</section>
  <footer><div class="mono">Generated by Chronicle · one unified item list powers every tab and search · ${escapeHtml(new Date(model.generatedAt).toLocaleString())}</div></footer>
</main>

<div class="overlay" id="overlay" role="dialog" aria-modal="true" aria-label="Search project brain">
  <div class="pal">
    <div class="pal-in"><input id="palInput" placeholder="Search features, files, decisions, roadmap, history..." autocomplete="off"><span class="esc">esc</span></div>
    <div class="pal-results" id="palResults"></div>
    <div class="pal-foot"><span>↑↓ navigate</span><span>enter open</span><span>esc close</span></div>
  </div>
</div>

<aside class="intent-drawer" id="intentDrawer" aria-label="Pending action intents">
  <div class="drawer-head"><div><strong>Pending intents</strong><span>Export these for the next agent session.</span></div><button type="button" id="closeIntentQueue" aria-label="Close action intent queue">×</button></div>
  <div class="intent-list" id="intentList"></div>
  <div class="intent-actions"><button type="button" id="copyIntents">Copy JSON</button><button type="button" id="downloadIntents">Download</button><button type="button" id="clearIntents">Clear</button></div>
</aside>

<script>window.__CHRONICLE_DATA__=${dataJson};${JS}</script>
</body>
</html>`;
}

function toClientData(model) {
  return {
    search: model.search,
  };
}

function tabButton(id, label, iconName, active = false) {
  return `<button data-tab="${id}" class="${active ? "on" : ""}" type="button">${icon(iconName)}${label}</button>`;
}

function overviewPanel(model, storePath, architecture, gitFacts) {
  return `<div class="hero"><p class="eyebrow">Project brain · last update ${escapeHtml(shortDate(model.lastUpdated))}</p><h1>${escapeHtml(model.projectName)}</h1><p class="tag">The private place to find or remember anything about this project: features, files, decisions, plans, and captured build history.</p></div>
  <section class="block no-top"><div class="grid g3">
    ${stat(model.stats.events, "timeline events")}
    ${stat(model.stats.features, "feature items")}
    ${stat(model.stats.files, "tracked files")}
    ${stat(model.stats.decisions, "decisions")}
    ${stat(model.stats.roadmap, "roadmap items")}
    ${stat(model.tech.length, "tech tags")}
  </div></section>
  <div class="privacy card"><strong>Private local brain.</strong><span>Rendered from ${escapeHtml(storePath)}. Public pages later must use public summaries only.</span></div>
  ${freshnessCard(gitFacts)}
  <div class="grid g2 overview-grid">
    <section><div class="block-head"><h2>In Progress</h2></div><div class="grid">${featureCards(model.features.filter((item) => item.status === "in_progress").slice(0, 4), model) || emptyCard("Nothing in progress yet.")}</div></section>
    <section><div class="block-head"><h2>Recent Activity</h2></div><div class="grid">${eventCards(model.events.slice(0, 4), model) || emptyCard("No events captured yet.")}</div></section>
  </div>
  ${architecturePanel(architecture)}
  <section class="block"><div class="block-head"><h2>Tech Stack Over Time</h2></div>${techList(model.tech)}</section>`;
}

function freshnessCard(gitFacts) {
  if (!gitFacts?.available) return "";
  const changed = gitFacts.changed_files?.length ?? 0;
  return `<div class="fresh card"><strong>${changed ? "Review freshness" : "Fresh at render time"}</strong><span>Git ${escapeHtml(gitFacts.branch || "detached")}@${escapeHtml(gitFacts.head || "unknown")}. ${changed ? `${changed} changed file${changed === 1 ? "" : "s"} in the working tree, so generated maps may need review.` : "No changed files were detected when this HTML was generated."}</span></div>`;
}

function architecturePanel(architecture) {
  if (!architecture) return "";
  return `<section class="block"><div class="block-head"><h2>Architecture Snapshot</h2><span class="src">${escapeHtml(architecture.packageManager)} · ${escapeHtml(architecture.packageName)}@${escapeHtml(architecture.packageVersion)}</span></div><div class="arch card"><div class="flow">${architecture.flow.map(([from, to]) => `<div><span>${escapeHtml(from)}</span><i></i><span>${escapeHtml(to)}</span></div>`).join("")}</div><div class="modules">${architecture.modules.map((module) => `<div class="module"><strong>${escapeHtml(module.name)}</strong><p>${escapeHtml(module.role)}</p><code>${escapeHtml(module.paths.slice(0, 3).join(" · "))}</code></div>`).join("")}</div></div></section>`;
}

function featuresPanel(model) {
  return `<div class="hero"><p class="eyebrow">Feature registry</p><h1>Features & plans</h1><p class="tag">Every feature item Chronicle knows about, including derived features from captured sessions.</p></div>
  <section class="block no-top"><div class="filters" id="featFilter"><button data-filter="all" class="on">All</button><button data-filter="completed">Shipped</button><button data-filter="in_progress">In progress</button><button data-filter="planned">Planned</button><button data-filter="idea">Ideas</button></div><div class="grid g2 feature-grid" id="featureGrid">${featureCards(model.features, model)}</div></section>`;
}

function filesPanel(model) {
  return `<div class="hero"><p class="eyebrow">File map</p><h1>Key files</h1><p class="tag">What each tracked file does, when it was last touched, and what it connects to.</p></div>
  <section class="block no-top"><div class="card file-list">${model.files.map((item) => fileRow(item, model)).join("") || `<div class="frow"><div>No tracked files yet.</div></div>`}</div></section>`;
}

function timelinePanel(model) {
  return `<div class="hero"><p class="eyebrow">Build history</p><h1>Timeline</h1><p class="tag">Session-by-session history from hooks and imported artifacts.</p></div>
  <section class="block no-top"><div class="timeline">${timelineGroups(model.events, model)}</div></section>`;
}

function decisionsPanel(model) {
  return `<div class="hero"><p class="eyebrow">Decision log</p><h1>Why things are the way they are</h1><p class="tag">Important reasoning, tradeoffs, and choices.</p></div>
  <section class="block no-top"><div class="grid">${decisionCards(model.decisions) || emptyCard("No decisions captured yet.")}</div></section>`;
}

function roadmapPanel(model) {
  return `<div class="hero"><p class="eyebrow">Roadmap</p><h1>What's planned</h1><p class="tag">Planned work from Chronicle items and future Superpowers plans.</p></div>
  <section class="block no-top"><div class="grid g3">${roadmapLanes(model.roadmap)}</div></section>`;
}

function stat(number, label) {
  return `<div class="card stat"><div class="n">${escapeHtml(number)}</div><div class="l">${escapeHtml(label)}</div></div>`;
}

function featureCards(features, model) {
  return features.map((item) => featureCard(item, model)).join("");
}

function featureCard(item, model) {
  return `<article class="card feat" id="card-${escapeHtml(item.id)}" data-status="${escapeHtml(item.status)}"><div class="top"><span class="badge st-${escapeHtml(item.status)}">${escapeHtml(STATUS_LABELS[item.status] ?? item.status)}</span><h3>${escapeHtml(item.title)}</h3></div><p>${escapeHtml(oneLine(item.summary || item.raw_summary))}</p>${chips(item.tech)}${fileChips(item.files, model)}${featureActions(item)}</article>`;
}

function eventCards(events, model) {
  return events.map((item) => eventCard(item, model)).join("");
}

function eventCard(item, model) {
  const featureLinks = (item.links?.features ?? []).map((id) => linkChip(labelForFeature(model, id), "features", id)).join("");
  return `<article class="card evt" id="card-${escapeHtml(item.id)}"><div class="top"><span class="badge b-${escapeHtml(item.type)}">${escapeHtml(EVENT_LABELS[item.type] ?? item.type)}</span><span class="src">${escapeHtml(item.source_tool ?? "unknown")}</span><span class="date">${escapeHtml(item.date)}</span></div><p>${escapeHtml(oneLine(item.title))}</p><div class="meta">${chips(item.tech)}${featureLinks}${item.files?.length ? `<span class="chip static">${item.files.length} file${item.files.length === 1 ? "" : "s"}</span>` : ""}</div></article>`;
}

function fileRow(item, model) {
  return `<div class="frow" id="card-${escapeHtml(item.id)}"><div class="path">${escapeHtml(item.data?.path ?? item.title)}</div><div class="role">${escapeHtml(item.data?.role ?? item.summary)}<div class="mini-links">${(item.links?.features ?? []).map((id) => linkChip(labelForFeature(model, id), "features", id)).join("")}</div></div><div class="touch">touched ${escapeHtml(item.date)}</div></div>`;
}

function decisionCards(decisions) {
  return decisions.map((item) => `<article class="card dec" id="card-${escapeHtml(item.id)}"><div class="top"><h3>${escapeHtml(item.title)}</h3><span class="date">${escapeHtml(item.date)}</span></div><p class="why">${escapeHtml(item.summary || item.raw_summary)}</p>${chips(item.tech)}</article>`).join("");
}

function roadmapLanes(roadmap) {
  const lanes = [
    ["in_progress", "Now"],
    ["planned", "Next"],
    ["idea", "Later / ideas"],
  ];
  return lanes.map(([status, label]) => `<div class="card lane"><h3>${label}</h3>${roadmap.filter((item) => item.status === status).map(planRow).join("") || `<div class="n">No items yet.</div>`}</div>`).join("");
}

function planRow(item) {
  return `<div class="item" id="card-${escapeHtml(item.id)}"><button class="tk intent-check" type="button" aria-label="Mark roadmap item completed" data-intent-action="set_roadmap_status" data-target="${escapeHtml(item.id)}" data-value="completed" data-intent-label="${escapeHtml(item.title)}"></button><div><div class="t">${escapeHtml(item.title)}</div><div class="n">${escapeHtml(oneLine(item.summary || item.raw_summary))}</div></div></div>`;
}

function featureActions(item) {
  const actions = [
    ["completed", "Mark shipped"],
    ["in_progress", "In progress"],
    ["planned", "Plan next"],
  ].filter(([status]) => status !== item.status);
  return `<div class="intent-row">${actions.map(([status, label]) => `<button type="button" data-intent-action="set_feature_status" data-target="${escapeHtml(item.id)}" data-value="${escapeHtml(status)}" data-intent-label="${escapeHtml(item.title)}">${escapeHtml(label)}</button>`).join("")}</div>`;
}

function timelineGroups(events, model) {
  const groups = new Map();
  for (const event of events) {
    const key = event.date || "Undated";
    groups.set(key, [...(groups.get(key) ?? []), event]);
  }
  return Array.from(groups.entries()).map(([date, items]) => `<div class="time-group"><div class="ver-node"><i></i></div><div class="ver-label">${escapeHtml(date)}<span class="vd">${items.length} item${items.length === 1 ? "" : "s"}</span></div><div class="ver-events">${items.map((item) => eventCard(item, model)).join("")}</div></div>`).join("") || emptyCard("No timeline events yet.");
}

function techList(tech) {
  if (!tech.length) return emptyCard("Tech tags will appear after more captures.");
  const max = Math.max(...tech.map((item) => item.count));
  return `<div class="card tech-list">${tech.map((item) => `<div class="tech-row"><span>${escapeHtml(item.name)}</span><div class="bar"><i style="width:${Math.max(12, (item.count / max) * 100)}%"></i></div><strong>${item.count}</strong></div>`).join("")}</div>`;
}

function chips(values = []) {
  return values.length ? `<div class="chips">${values.map((value) => `<span class="chip static">${escapeHtml(value)}</span>`).join("")}</div>` : "";
}

function fileChips(files = [], model) {
  if (!files.length) return "";
  return `<div class="links"><span class="lbl">files</span>${files.slice(0, 6).map((filePath) => {
    const file = model.files.find((item) => (item.data?.path ?? item.title) === filePath);
    return file ? linkChip(filePath.split("/").pop(), "files", file.id) : `<span class="chip static">${escapeHtml(filePath.split("/").pop())}</span>`;
  }).join("")}</div>`;
}

function linkChip(label, tab, id) {
  return `<button class="chip" type="button" data-go-tab="${escapeHtml(tab)}" data-go-id="${escapeHtml(id)}">${escapeHtml(label)}</button>`;
}

function labelForFeature(model, id) {
  return clip(model.features.find((item) => item.id === id)?.title ?? id, 42);
}

function clip(value, length) {
  const text = oneLine(value);
  return text.length > length ? `${text.slice(0, length - 3)}...` : text;
}

function icon(name) {
  const paths = {
    search: `<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>`,
    overview: `<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>`,
    star: `<path d="M12 2l2.7 5.5 6.1.9-4.4 4.3 1 6.1L12 16l-5.4 2.8 1-6.1-4.4-4.3 6.1-.9L12 2z"/>`,
    folder: `<path d="M4 6.5A2.5 2.5 0 0 1 6.5 4H10l2 2h5.5A2.5 2.5 0 0 1 20 8.5V18a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6.5z"/>`,
    clock: `<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>`,
    scale: `<path d="M12 3v18M5 8l7-5 7 5M5 8l-2 6a4 4 0 0 0 8 0L9 8M19 8l-2 6a4 4 0 0 0 8 0l-2-6"/>`,
    roadmap: `<path d="M5 19V7a2 2 0 0 1 2-2h10"/><path d="M9 11h7M9 15h4"/><path d="M16 3l4 4-4 4"/>`,
  };
  return `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths[name] ?? ""}</svg>`;
}

function emptyCard(text) {
  return `<div class="card empty-state">${escapeHtml(text)}</div>`;
}

function oneLine(value) {
  return String(value ?? "").replace(/\s+/g, " ").trim().slice(0, 220);
}

function shortDate(value) {
  return value ? new Date(value).toLocaleDateString() : "unknown";
}

const CSS = `
:root{--accent:#5b50e8;--accent-ink:#fff;--radius:10px;--maxw:1080px;--bg:#f4f2ec;--surface:#fbfaf6;--surface-2:#efece3;--ink:#1a1813;--muted:#6c6557;--line:rgba(26,24,19,.13);--line-strong:rgba(26,24,19,.27);--grid:rgba(26,24,19,.045);--green:#2f8f3f;--amber:#a96f12;--blue:#3f6fe0;--violet:#7d4fc0;--red:#c8463d;--shadow:0 1px 0 rgba(26,24,19,.04),0 20px 44px -34px rgba(26,24,19,.5)}
html[data-theme="dark"]{--bg:#101218;--surface:#181b23;--surface-2:#20242e;--ink:#ece9e1;--muted:#aaa393;--line:rgba(236,233,225,.12);--line-strong:rgba(236,233,225,.26);--grid:rgba(236,233,225,.035);--green:#6cd47a;--amber:#e2b25a;--blue:#85a9ff;--violet:#bd97ec;--red:#ef8079;--shadow:0 1px 0 rgba(0,0,0,.3),0 24px 50px -34px rgba(0,0,0,.8)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:16px;line-height:1.55;background-image:radial-gradient(var(--grid) 1px,transparent 1px);background-size:26px 26px;background-position:-13px -13px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.wrap{max-width:var(--maxw);margin:0 auto;padding:0 22px}.topbar{position:sticky;top:0;z-index:50;background:color-mix(in srgb,var(--bg) 88%,transparent);backdrop-filter:blur(10px);border-bottom:1px solid var(--line)}.topbar-in{max-width:var(--maxw);margin:0 auto;padding:12px 22px;display:flex;align-items:center;gap:14px}.brand{display:flex;align-items:center;gap:9px;font-weight:800;font-size:17px}.brand .dot{width:10px;height:10px;border-radius:3px;background:var(--accent);box-shadow:0 0 0 4px color-mix(in srgb,var(--accent) 22%,transparent)}.proj{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;color:var(--muted);border:1px solid var(--line);padding:3px 8px;border-radius:999px}.spacer{flex:1}.searchbtn,.queuebtn{display:flex;align-items:center;gap:10px;background:var(--surface-2);border:1px solid var(--line);border-radius:10px;padding:8px 12px;cursor:pointer;color:var(--muted);font:inherit;font-size:14px}.searchbtn{min-width:220px}.queuebtn span{min-width:20px;text-align:center;border-radius:999px;background:var(--accent);color:var(--accent-ink);font:800 11px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;padding:2px 6px}.searchbtn:hover,.queuebtn:hover{border-color:var(--line-strong)}.searchbtn svg,.tabs svg{width:15px;height:15px;flex:0 0 auto}.searchbtn .kbd{margin-left:auto}.kbd,.esc{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;border:1px solid var(--line);border-radius:6px;padding:1px 6px;color:var(--muted)}.tabbar{border-bottom:1px solid var(--line);overflow-x:auto}.tabs{display:flex;gap:2px;max-width:var(--maxw);margin:0 auto;padding:0 22px}.tabs button{border:0;background:transparent;color:var(--muted);font:inherit;font-weight:650;font-size:13.5px;padding:13px 14px;cursor:pointer;border-bottom:2px solid transparent;margin-bottom:-1px;white-space:nowrap;display:flex;align-items:center;gap:7px}.tabs button.on{color:var(--ink);border-bottom-color:var(--accent)}.ct{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10.5px;background:var(--surface-2);border:1px solid var(--line);border-radius:6px;padding:0 5px}.panel{display:none}.panel.on{display:block}.hero{padding:38px 0 18px}.eyebrow{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11.5px;letter-spacing:.15em;text-transform:uppercase;color:var(--accent);font-weight:700;margin:0 0 11px}.hero h1{font-weight:850;font-size:clamp(32px,5vw,52px);line-height:1;letter-spacing:0;margin:0 0 11px}.hero p.tag{font-size:clamp(15px,2vw,18px);color:var(--muted);max-width:62ch;margin:0}section.block{padding:32px 0;border-top:1px solid var(--line)}section.no-top{border-top:0;padding-top:10px}.block-head{display:flex;align-items:center;gap:12px;margin:0 0 18px;flex-wrap:wrap}.block-head h2{font-weight:780;font-size:clamp(19px,3vw,25px);margin:0}.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow)}.grid{display:grid;gap:12px}.g2{grid-template-columns:1fr 1fr}.g3{grid-template-columns:repeat(3,1fr)}.stat{padding:16px 18px}.stat .n{font-weight:850;font-size:28px;line-height:1}.stat .l{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10.5px;letter-spacing:.05em;text-transform:uppercase;color:var(--muted);margin-top:7px}.privacy,.fresh{display:flex;gap:10px;align-items:flex-start;padding:14px 16px;color:var(--muted);margin-bottom:22px;flex-wrap:wrap}.fresh{margin-top:-8px}.privacy strong,.fresh strong{color:var(--ink)}.privacy span,.fresh span{min-width:0;flex:1 1 260px}.overview-grid{margin-top:8px}.badge{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;padding:3px 8px;border-radius:7px;display:inline-block}.st-completed{background:color-mix(in srgb,var(--green) 17%,var(--surface));color:var(--green)}.st-in_progress{background:color-mix(in srgb,var(--amber) 20%,var(--surface));color:var(--amber)}.st-planned{background:color-mix(in srgb,var(--blue) 18%,var(--surface));color:var(--blue)}.st-idea{background:var(--surface-2);color:var(--muted)}.st-blocked{background:color-mix(in srgb,var(--red) 17%,var(--surface));color:var(--red)}.st-unknown{background:var(--surface-2);color:var(--muted)}.b-feature_added{background:color-mix(in srgb,var(--green) 17%,var(--surface));color:var(--green)}.b-bugfix{background:color-mix(in srgb,var(--red) 17%,var(--surface));color:var(--red)}.b-refactor{background:color-mix(in srgb,var(--amber) 19%,var(--surface));color:var(--amber)}.b-dependency_changed{background:color-mix(in srgb,var(--blue) 18%,var(--surface));color:var(--blue)}.b-decision{background:color-mix(in srgb,var(--violet) 18%,var(--surface));color:var(--violet)}.b-version_bump{background:var(--accent);color:var(--accent-ink)}.b-note{background:var(--surface-2);color:var(--muted)}.chip{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;background:var(--surface-2);border:1px solid var(--line);border-radius:999px;padding:3px 9px;color:var(--ink);display:inline-block;cursor:pointer}.chip:hover{border-color:var(--accent);color:var(--accent)}.chip.static{cursor:default}.chip.static:hover{border-color:var(--line);color:var(--ink)}.feat{padding:16px 18px}.feat .top{display:flex;align-items:center;gap:9px;margin-bottom:9px;flex-wrap:wrap}.feat h3{font-size:17px;margin:0;line-height:1.25}.feat p,.evt p{font-size:14px;color:var(--muted);margin:0 0 12px}.chips,.links,.mini-links,.meta{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.links .lbl{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em;margin-right:2px}.filters{display:inline-flex;gap:3px;background:var(--surface-2);border:1px solid var(--line);border-radius:9px;padding:3px;margin-bottom:14px;flex-wrap:wrap}.filters button{border:0;background:transparent;color:var(--muted);font:inherit;font-size:12.5px;font-weight:650;padding:5px 11px;border-radius:7px;cursor:pointer}.filters button.on{background:var(--accent);color:var(--accent-ink)}.frow{display:grid;grid-template-columns:1.35fr 1.65fr auto;gap:14px;align-items:center;padding:13px 16px;border-top:1px solid var(--line)}.frow:first-child{border-top:0}.path{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:13px;font-weight:600;word-break:break-all}.role{font-size:13.5px;color:var(--muted)}.touch{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;color:var(--muted);text-align:right;white-space:nowrap}.arch{padding:16px;display:grid;gap:16px}.flow{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.flow div{display:grid;grid-template-columns:minmax(0,1fr) 28px minmax(0,1fr);align-items:center;gap:8px}.flow span{border:1px solid var(--line);background:var(--surface-2);border-radius:8px;padding:8px 10px;font-size:12px;font-weight:700}.flow i{height:2px;background:var(--accent);position:relative}.flow i::after{content:"";position:absolute;right:0;top:-4px;border:5px solid transparent;border-left-color:var(--accent);border-right:0}.modules{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.module{border:1px solid var(--line);border-radius:8px;padding:12px;background:color-mix(in srgb,var(--surface-2) 42%,transparent)}.module strong{font-size:13px}.module p{color:var(--muted);font-size:12px;margin:4px 0 8px}.module code{font:650 10.5px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:var(--muted);word-break:break-all}.timeline{position:relative;padding-left:30px}.timeline::before{content:"";position:absolute;left:8px;top:5px;bottom:5px;width:2px;background:var(--line-strong)}.time-group{position:relative;margin-bottom:6px}.ver-node{position:absolute;left:-30px;top:1px;width:18px;height:18px;border-radius:50%;background:var(--bg);border:2px solid var(--accent);display:grid;place-items:center}.ver-node i{width:6px;height:6px;border-radius:50%;background:var(--accent)}.ver-label{font-weight:850;font-size:18px;margin:0 0 2px;display:flex;gap:9px;align-items:center}.vd{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-weight:500;font-size:11px;color:var(--muted)}.ver-events{margin:12px 0 26px;display:grid;gap:10px}.evt{padding:13px 16px}.evt .top{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-bottom:6px}.src{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:9.5px;color:var(--muted);border:1px solid var(--line);border-radius:6px;padding:2px 6px}.date{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10.5px;color:var(--muted);margin-left:auto}.dec{padding:17px 19px}.dec .top{display:flex;align-items:baseline;gap:10px;margin-bottom:8px}.dec h3{font-size:16.5px;margin:0}.why{font-size:13.5px;color:var(--muted);margin:0 0 10px}.lane{padding:16px 18px}.lane h3{font-size:15px;margin:0 0 12px}.lane .item{display:flex;gap:9px;align-items:flex-start;padding:9px 0;border-top:1px solid var(--line)}.lane .item:first-of-type{border-top:0}.tk{flex:0 0 auto;margin-top:3px;width:13px;height:13px;border-radius:4px;border:2px solid var(--line-strong);background:transparent;cursor:pointer;padding:0}.tk:hover{border-color:var(--accent)}.t{font-size:14px}.n{font-size:12px;color:var(--muted);margin-top:1px}.tech-list{padding:14px;display:grid;gap:12px}.tech-row{display:grid;grid-template-columns:120px 1fr 28px;gap:10px;align-items:center}.bar{height:10px;background:var(--surface-2);border-radius:999px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--blue))}.empty-state{padding:18px;color:var(--muted)}.intent-row{display:flex;gap:6px;flex-wrap:wrap;margin-top:13px}.intent-row button,.intent-actions button{border:1px solid var(--line);border-radius:8px;background:var(--surface-2);color:var(--ink);font:700 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;padding:6px 9px;cursor:pointer}.intent-row button:hover,.intent-actions button:hover{border-color:var(--accent);color:var(--accent)}.intent-pending{outline:2px solid color-mix(in srgb,var(--accent) 45%,transparent);outline-offset:2px}.intent-drawer{position:fixed;right:18px;top:74px;bottom:18px;width:min(380px,calc(100vw - 36px));z-index:90;background:var(--surface);border:1px solid var(--line-strong);border-radius:14px;box-shadow:0 24px 70px -32px rgba(0,0,0,.6);display:none;grid-template-rows:auto 1fr auto;overflow:hidden}.intent-drawer.on{display:grid}.drawer-head{display:flex;justify-content:space-between;gap:12px;padding:16px;border-bottom:1px solid var(--line)}.drawer-head div{display:grid;gap:3px}.drawer-head span{color:var(--muted);font-size:12px}.drawer-head button{border:0;background:transparent;color:var(--muted);font-size:24px;cursor:pointer;line-height:1}.intent-list{overflow:auto;padding:12px;display:grid;gap:8px;align-content:start}.intent-empty{border:1px dashed var(--line);border-radius:10px;padding:14px;color:var(--muted);font-size:13px}.intent-item{border:1px solid var(--line);border-radius:10px;padding:10px;display:grid;gap:5px}.intent-item strong{font-size:13px}.intent-item span{color:var(--muted);font:650 11px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.intent-actions{display:flex;gap:8px;padding:12px;border-top:1px solid var(--line);flex-wrap:wrap}.flash{animation:flash 1.4s ease}@keyframes flash{0%,40%{box-shadow:0 0 0 2px var(--accent),var(--shadow)}100%{box-shadow:0 0 0 0 transparent,var(--shadow)}}footer{padding:40px 0 60px;text-align:center;border-top:1px solid var(--line);margin-top:14px}footer .mono{font-size:11.5px;color:var(--muted)}.overlay{position:fixed;inset:0;z-index:100;display:none;background:color-mix(in srgb,var(--bg) 55%,rgba(0,0,0,.5));backdrop-filter:blur(4px);padding:12vh 16px 16px}.overlay.on{display:block}.pal{max-width:620px;margin:0 auto;background:var(--surface);border:1px solid var(--line-strong);border-radius:16px;box-shadow:0 30px 80px -30px rgba(0,0,0,.6);overflow:hidden}.pal-in{display:flex;align-items:center;gap:11px;padding:15px 18px;border-bottom:1px solid var(--line)}.pal-in input{flex:1;border:0;background:transparent;color:var(--ink);font:inherit;font-size:17px;outline:none}.pal-results{max-height:52vh;overflow:auto;padding:8px}.pgrp{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);padding:10px 12px 5px}.res{display:flex;align-items:center;gap:11px;padding:9px 12px;border-radius:10px;cursor:pointer}.res.sel,.res:hover{background:var(--surface-2)}.ki{flex:0 0 auto;width:34px;height:26px;border-radius:7px;display:grid;place-items:center;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10px;font-weight:800;background:color-mix(in srgb,var(--accent) 18%,var(--surface));color:var(--accent)}.rt{font-size:14.5px;font-weight:650;line-height:1.2}.rs{font-size:12px;color:var(--muted);line-height:1.3}.rk{margin-left:auto;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10px;color:var(--muted)}.res-empty{padding:26px;text-align:center;color:var(--muted);font-size:14px}.pal-foot{border-top:1px solid var(--line);padding:9px 14px;display:flex;gap:16px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10.5px;color:var(--muted)}button{touch-action:manipulation}@media(max-width:820px){.g3,.flow,.modules{grid-template-columns:1fr 1fr}.g2{grid-template-columns:1fr}.searchbtn{min-width:unset}.frow{grid-template-columns:1fr;gap:6px}.touch{text-align:left}}@media(max-width:600px){.g3,.flow,.modules{grid-template-columns:1fr}.flow div{grid-template-columns:1fr}.flow i{display:none}.topbar-in{align-items:flex-start;flex-wrap:wrap}.searchbtn{width:100%}.tabs button{padding:12px 10px}.hero{padding-top:26px}.intent-drawer{right:10px;left:10px;width:auto}}
`;

const JS = `
const DATA=window.__CHRONICLE_DATA__;
const overlay=document.getElementById("overlay"),palInput=document.getElementById("palInput"),palResults=document.getElementById("palResults");
let sel=0,current=[];
const GROUP={features:"Features",files:"Files",decisions:"Decisions",roadmap:"Roadmap",events:"Timeline"};
const INTENT_KEY="chronicle-action-intents-v1";
const intentDrawer=document.getElementById("intentDrawer"),intentList=document.getElementById("intentList"),intentCount=document.getElementById("intentCount");
function showTab(tab){document.querySelectorAll("#tabs button").forEach(button=>button.classList.toggle("on",button.dataset.tab===tab));document.querySelectorAll(".panel").forEach(panel=>panel.classList.toggle("on",panel.dataset.panel===tab));}
document.getElementById("tabs").addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;showTab(button.dataset.tab);window.scrollTo({top:0,behavior:"smooth"});});
document.addEventListener("click",event=>{const button=event.target.closest("[data-go-tab]");if(!button)return;goTo(button.dataset.goTab,button.dataset.goId);});
document.addEventListener("click",event=>{const button=event.target.closest("[data-intent-action]");if(!button)return;recordIntent(button);});
function goTo(tab,id){closeSearch();showTab(tab === "events" ? "timeline" : tab);setTimeout(()=>{const el=document.getElementById("card-"+id);if(el){el.scrollIntoView({behavior:"smooth",block:"center"});el.classList.remove("flash");void el.offsetWidth;el.classList.add("flash");}},80);}window.goTo=goTo;
function search(query){query=query.trim().toLowerCase();if(!query)return DATA.search.slice(0,8);const terms=query.split(/\s+/);return DATA.search.map(row=>{let score=0;for(const term of terms){if(row.haystack.includes(term))score+=row.title.toLowerCase().includes(term)?3:1;}return Object.assign({},row,{score:score});}).filter(row=>row.score>0).sort((a,b)=>b.score-a.score).slice(0,14);}
function renderResults(){if(!current.length){palResults.innerHTML='<div class="res-empty">No matches. Try a feature, file, decision, or keyword.</div>';return;}let html="",last=null;current.forEach((row,index)=>{if(row.tab!==last){html+='<div class="pgrp">'+GROUP[row.tab]+'</div>';last=row.tab;}html+='<div class="res '+(index===sel?'sel':'')+'" data-i="'+index+'"><span class="ki">'+row.token+'</span><div style="min-width:0"><div class="rt">'+escapeHtml(row.title)+'</div><div class="rs">'+escapeHtml(row.subtitle||"")+'</div></div><span class="rk">enter</span></div>';});palResults.innerHTML=html;}
function runSearch(){current=search(palInput.value);sel=0;renderResults();}
function openSearch(){overlay.classList.add("on");palInput.value="";current=search("");sel=0;renderResults();setTimeout(()=>palInput.focus(),30);}function closeSearch(){overlay.classList.remove("on");}
document.getElementById("openSearch").addEventListener("click",openSearch);overlay.addEventListener("click",event=>{if(event.target===overlay)closeSearch();});palInput.addEventListener("input",runSearch);palResults.addEventListener("click",event=>{const row=event.target.closest(".res");if(row){const item=current[Number(row.dataset.i)];goTo(item.tab,item.id);}});palResults.addEventListener("mousemove",event=>{const row=event.target.closest(".res");if(row){sel=Number(row.dataset.i);document.querySelectorAll(".res").forEach(entry=>entry.classList.toggle("sel",entry===row));}});
document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();overlay.classList.contains("on")?closeSearch():openSearch();return;}if(!overlay.classList.contains("on"))return;if(event.key==="Escape")closeSearch();else if(event.key==="ArrowDown"){event.preventDefault();sel=Math.min(sel+1,current.length-1);renderResults();}else if(event.key==="ArrowUp"){event.preventDefault();sel=Math.max(sel-1,0);renderResults();}else if(event.key==="Enter"&&current[sel]){goTo(current[sel].tab,current[sel].id);}});
const featFilter=document.getElementById("featFilter"),featureGrid=document.getElementById("featureGrid");if(featFilter){featFilter.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;document.querySelectorAll("#featFilter button").forEach(entry=>entry.classList.toggle("on",entry===button));document.querySelectorAll(".feature-grid .feat").forEach(card=>{card.style.display=button.dataset.filter==="all"||card.dataset.status===button.dataset.filter?"":"none";});});}
function escapeHtml(value){return String(value==null?"":value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
function loadIntents(){try{return JSON.parse(localStorage.getItem(INTENT_KEY)||"[]");}catch(error){return[];}}
function saveIntents(intents){localStorage.setItem(INTENT_KEY,JSON.stringify(intents));renderIntents();}
function recordIntent(button){const intent={action:button.dataset.intentAction,target:button.dataset.target,value:button.dataset.value,label:button.dataset.intentLabel||button.dataset.target,created_at:new Date().toISOString()};const intents=loadIntents().filter(item=>!(item.action===intent.action&&item.target===intent.target));intents.push(intent);saveIntents(intents);const card=document.getElementById("card-"+intent.target);if(card)card.classList.add("intent-pending");button.textContent="Queued";intentDrawer.classList.add("on");}
function intentPayload(){return {schema_version:1,generated_by:"chronicle-project-brain",intents:loadIntents().map(item=>({action:item.action,target:item.target,value:item.value,created_at:item.created_at}))};}
function renderIntents(){const intents=loadIntents();intentCount.textContent=String(intents.length);if(!intents.length){intentList.innerHTML='<div class="intent-empty">No pending intents yet. Use feature and roadmap controls to queue safe changes.</div>';return;}intentList.innerHTML=intents.map(intent=>'<div class="intent-item"><strong>'+escapeHtml(intent.label||intent.target)+'</strong><span>'+escapeHtml(intent.action)+' / '+escapeHtml(intent.value)+'</span><span>'+escapeHtml(intent.target)+'</span></div>').join("");}
async function copyIntents(){const text=JSON.stringify(intentPayload(),null,2);if(navigator.clipboard){await navigator.clipboard.writeText(text);return;}window.prompt("Copy Chronicle actions JSON",text);}
function downloadIntents(){const blob=new Blob([JSON.stringify(intentPayload(),null,2)+"\\n"],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="chronicle-actions.json";link.click();URL.revokeObjectURL(url);}
document.getElementById("openIntentQueue").addEventListener("click",()=>intentDrawer.classList.add("on"));document.getElementById("closeIntentQueue").addEventListener("click",()=>intentDrawer.classList.remove("on"));document.getElementById("copyIntents").addEventListener("click",copyIntents);document.getElementById("downloadIntents").addEventListener("click",downloadIntents);document.getElementById("clearIntents").addEventListener("click",()=>saveIntents([]));renderIntents();
`;
