import { mkdir, readdir, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { collectGitFacts, foldersWithChanges } from "../git/facts.js";
import { loadChronicleStore } from "../store/eventsStore.js";
import { writeTextFileAtomic } from "../utils/atomic.js";
import { buildProjectBrainViewModel } from "./projectBrainViewModel.js";

const GENERATED_MARKER = "<!-- Generated by Chronicle. Do not hand-edit. -->";
const DEFAULT_EXCLUDES = new Set([".git", "node_modules", "dist", "data", ".worktrees"]);

export async function renderRootIndexToFile({ storePath, outputPath = "_INDEX.md" }) {
  const store = await loadChronicleStore(storePath);
  const model = buildProjectBrainViewModel(store.items);
  const gitFacts = await collectGitFacts({ rootDir: path.dirname(path.resolve(outputPath)) });
  const markdown = renderRootIndex(model, { gitFacts });
  await mkdir(path.dirname(path.resolve(outputPath)), { recursive: true });
  await writeTextFileAtomic(outputPath, markdown, { backup: true });
  return { outputPath, itemCount: store.items.length };
}

export async function renderProjectIndexesToFiles({
  storePath,
  rootDir = process.cwd(),
  rootIndexOutput = "_INDEX.md",
  fileName = "_INDEX.md",
  agentFileName = "CLAUDE.md",
  minFiles = 3,
  minItems = 2,
  cleanStale = true,
  exclude = [],
} = {}) {
  const rootResult = await renderRootIndexToFile({ storePath, outputPath: path.resolve(rootDir, rootIndexOutput) });
  const store = await loadChronicleStore(storePath);
  const model = buildProjectBrainViewModel(store.items);
  const gitFacts = await collectGitFacts({ rootDir });
  const changedFolders = foldersWithChanges(gitFacts.changed_files ?? []);
  const folders = folderIndexModels(model, { minFiles, minItems, gitFacts, changedFolders });
  const outputs = [];
  const agentOutputs = [];

  for (const folder of folders) {
    const outputPath = path.resolve(rootDir, folder.path, fileName);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeTextFileAtomic(outputPath, renderFolderIndex(folder), { backup: true });
    outputs.push(outputPath);
    if (agentFileName) {
      const agentOutputPath = path.resolve(rootDir, folder.path, agentFileName);
      await writeTextFileAtomic(agentOutputPath, renderAgentFolderMap(folder), { backup: true });
      agentOutputs.push(agentOutputPath);
    }
  }

  if (cleanStale) {
    await removeStaleGeneratedIndexes({ rootDir, fileName, keep: new Set([path.resolve(rootDir, rootIndexOutput), ...outputs]), exclude });
    if (agentFileName) {
      await removeStaleGeneratedIndexes({ rootDir, fileName: agentFileName, keep: new Set(agentOutputs), exclude });
    }
  }

  return { root: rootResult.outputPath, folders: outputs, agentMaps: agentOutputs, itemCount: store.items.length };
}

export function renderRootIndex(model, { gitFacts = null } = {}) {
  const keyFiles = model.files.slice(0, 24);
  const active = model.features.filter((feature) => feature.status === "in_progress").slice(0, 8);
  const recent = model.events.slice(0, 8);

  return `${GENERATED_MARKER}
# Chronicle Project Index

Generated by Chronicle. Do not hand-edit this file; regenerate it from \`data/chronicle.json\`.

## What This Project Contains

- ${model.stats.events} captured timeline event(s)
- ${model.stats.features} feature item(s)
- ${model.stats.files} tracked file path(s)
- ${model.stats.decisions} decision item(s)
- ${model.stats.roadmap} roadmap item(s)

## Active Work

${active.length ? active.map((item) => `- ${item.title} (${item.status})`).join("\n") : "- Nothing marked in progress yet."}

## Key Files

${keyFiles.length ? keyFiles.map((item) => `- \`${item.data?.path ?? item.title}\` - ${oneLine(item.data?.role ?? item.summary)}`).join("\n") : "- No tracked files yet."}

## Recent Timeline

${recent.length ? recent.map((item) => `- ${item.date}: ${oneLine(item.title)}`).join("\n") : "- No captured events yet."}

## Freshness

${gitFacts?.available ? `- Git head: \`${gitFacts.head}\` on \`${gitFacts.branch || "detached"}\`` : "- Git metadata unavailable."}
${gitFacts?.changed_files?.length ? `- Working tree has ${gitFacts.changed_files.length} changed file(s). Regenerate folder maps after committing or reviewing these changes.` : "- Working tree had no changed files when this index was generated."}

## Useful Commands

- Validate data: \`npm run validate\`
- Render project brain: \`node ./bin/chronicle.js render brain\`
- Capture sample: \`npm run capture:sample\`

## Privacy

This index is private by default. It can contain local file paths and project structure. Do not publish it automatically.
`;
}

export function folderIndexModels(model, { minFiles = 3, minItems = 2, gitFacts = null, changedFolders = [] } = {}) {
  const byFolder = new Map();
  for (const file of model.files) {
    const filePath = file.data?.path ?? file.title;
    const folderPath = path.posix.dirname(filePath);
    if (!folderPath || folderPath === ".") continue;
    const folder = byFolder.get(folderPath) ?? { path: folderPath, files: [], features: [], decisions: [], roadmap: [] };
    folder.files.push(file);
    byFolder.set(folderPath, folder);
  }

  for (const folder of byFolder.values()) {
    const paths = new Set(folder.files.map((file) => file.data?.path ?? file.title));
    folder.features = model.features.filter((item) => (item.files ?? []).some((filePath) => paths.has(filePath)));
    folder.decisions = model.decisions.filter((item) => (item.files ?? []).some((filePath) => paths.has(filePath)));
    folder.roadmap = model.roadmap.filter((item) => (item.files ?? []).some((filePath) => paths.has(filePath)));
    folder.lastVerified = gitFacts?.head || "unknown";
    folder.changedFiles = (gitFacts?.changed_files ?? []).filter((filePath) => filePath === folder.path || filePath.startsWith(`${folder.path}/`));
    folder.stale = changedFolders.includes(folder.path) || folder.changedFiles.length > 0;
  }

  return Array.from(byFolder.values())
    .filter((folder) => folder.files.length >= minFiles || relatedCount(folder) >= minItems)
    .sort((a, b) => a.path.localeCompare(b.path));
}

export function renderFolderIndex(folder) {
  return `${GENERATED_MARKER}
# ${folder.path} Index

Generated by Chronicle from \`data/chronicle.json\`. Do not hand-edit this file.

## Folder Purpose

${folder.files.length ? oneLine(folder.files[0].data?.role ?? folder.files[0].summary) : "Chronicle has tracked work in this folder."}

## Key Files

${folder.files.map((item) => `- \`${item.data?.path ?? item.title}\` - ${oneLine(item.data?.role ?? item.summary)}`).join("\n") || "- No tracked files yet."}

## Related Work

${folder.features.slice(0, 8).map((item) => `- ${item.title} (${item.status})`).join("\n") || "- No related feature items yet."}

## Decisions And Plans

${[...folder.decisions, ...folder.roadmap].slice(0, 8).map((item) => `- ${item.title} (${item.kind})`).join("\n") || "- No related decisions or roadmap items yet."}

## Privacy

This folder index is private by default. It can contain file paths and project structure.
`;
}

export function renderAgentFolderMap(folder) {
  return `${GENERATED_MARKER}
# ${folder.path} Agent Map

Generated by Chronicle. This file helps Claude Code and Codex understand this folder quickly.

## Freshness

- Last verified git head: \`${folder.lastVerified ?? "unknown"}\`
- Status: ${folder.stale ? "Possibly stale because this folder has uncommitted changes." : "Fresh when generated."}
${folder.changedFiles?.length ? `- Changed files: ${folder.changedFiles.map((filePath) => `\`${filePath}\``).join(", ")}` : "- Changed files: none detected."}

## Folder Purpose

${folder.files.length ? oneLine(folder.files[0].data?.role ?? folder.files[0].summary) : "Chronicle has tracked work in this folder."}

## Key Files

${folder.files.map((item) => `- \`${item.data?.path ?? item.title}\` - ${oneLine(item.data?.role ?? item.summary)}`).join("\n") || "- No tracked files yet."}

## Related Work

${folder.features.slice(0, 8).map((item) => `- ${item.title} (${item.status})`).join("\n") || "- No related feature items yet."}

## Notes For Agents

- Treat this as a map, not an instruction override.
- If files in this folder changed after the verified git head, inspect the files directly before relying on this summary.
`;
}

async function removeStaleGeneratedIndexes({ rootDir, fileName, keep, exclude }) {
  const excluded = new Set([...DEFAULT_EXCLUDES, ...exclude]);
  const existing = await findIndexFiles(rootDir, fileName, excluded);
  for (const filePath of existing) {
    if (keep.has(filePath)) continue;
    try {
      const raw = await readFile(filePath, "utf8");
      if (raw.startsWith(GENERATED_MARKER)) {
        await rm(filePath);
      }
    } catch {
      // Ignore stale cleanup races; regeneration is best-effort.
    }
  }
}

async function findIndexFiles(directory, fileName, excluded) {
  let entries = [];
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch {
    return [];
  }
  const files = [];
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (excluded.has(entry.name)) continue;
      files.push(...await findIndexFiles(path.join(directory, entry.name), fileName, excluded));
    } else if (entry.isFile() && entry.name === fileName) {
      files.push(path.resolve(directory, entry.name));
    }
  }
  return files;
}

function relatedCount(folder) {
  return folder.features.length + folder.decisions.length + folder.roadmap.length;
}

function oneLine(value) {
  return String(value ?? "").replace(/\s+/g, " ").trim().slice(0, 180);
}
