import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadChronicleStore } from "../store/eventsStore.js";
import { buildProjectBrainViewModel } from "./projectBrainViewModel.js";

export async function renderRootIndexToFile({ storePath, outputPath = "_INDEX.md" }) {
  const store = await loadChronicleStore(storePath);
  const model = buildProjectBrainViewModel(store.items);
  const markdown = renderRootIndex(model);
  await mkdir(path.dirname(path.resolve(outputPath)), { recursive: true });
  await writeFile(outputPath, markdown, "utf8");
  return { outputPath, itemCount: store.items.length };
}

export function renderRootIndex(model) {
  const keyFiles = model.files.slice(0, 24);
  const active = model.features.filter((feature) => feature.status === "in_progress").slice(0, 8);
  const recent = model.events.slice(0, 8);

  return `# Chronicle Project Index

Generated by Chronicle. Do not hand-edit this file; regenerate it from \`data/chronicle.json\`.

## What This Project Contains

- ${model.stats.events} captured timeline event(s)
- ${model.stats.features} feature item(s)
- ${model.stats.files} tracked file path(s)
- ${model.stats.decisions} decision item(s)
- ${model.stats.roadmap} roadmap item(s)

## Active Work

${active.length ? active.map((item) => `- ${item.title} (${item.status})`).join("\n") : "- Nothing marked in progress yet."}

## Key Files

${keyFiles.length ? keyFiles.map((item) => `- \`${item.data?.path ?? item.title}\` - ${oneLine(item.data?.role ?? item.summary)}`).join("\n") : "- No tracked files yet."}

## Recent Timeline

${recent.length ? recent.map((item) => `- ${item.date}: ${oneLine(item.title)}`).join("\n") : "- No captured events yet."}

## Useful Commands

- Validate data: \`npm run validate\`
- Render project brain: \`node ./bin/chronicle.js render brain\`
- Capture sample: \`npm run capture:sample\`

## Privacy

This index is private by default. It can contain local file paths and project structure. Do not publish it automatically.
`;
}

function oneLine(value) {
  return String(value ?? "").replace(/\s+/g, " ").trim().slice(0, 180);
}
