import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { scanTextForSafety } from "../safety/redaction.js";
import { loadChronicleStore } from "../store/eventsStore.js";
import { escapeHtml } from "../utils/html.js";

const TYPE_LABELS = {
  feature_added: "Feature",
  bugfix: "Fix",
  refactor: "Refactor",
  dependency_changed: "Stack",
  version_bump: "Version",
  decision: "Decision",
  note: "Note",
};

export async function renderPublicBuildPageToFile({ storePath, outputPath, version }) {
  const store = await loadChronicleStore(storePath);
  const html = renderPublicBuildPage(store.items, { version });
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, html, "utf8");
  return { outputPath, ...buildPublicBuildModel(store.items, { version }) };
}

export function renderPublicBuildPage(items, { version = "draft" } = {}) {
  const model = buildPublicBuildModel(items, { version });

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Chronicle Build Log - ${escapeHtml(version)}</title>
<style>${CSS}</style>
</head>
<body>
<main class="shell">
  <section class="hero">
    <p class="eyebrow">Build in public / ${escapeHtml(version)}</p>
    <h1>Chronicle Build Log</h1>
    <p class="lede">A public-safe changelog generated from items explicitly marked public.</p>
  </section>

  <section class="release-card">
    <div>
      <span class="label">Current update</span>
      <h2>${escapeHtml(model.headline)}</h2>
      <p>${escapeHtml(model.story)}</p>
    </div>
    <dl>
      <div><dt>Public updates</dt><dd>${model.updates.length}</dd></div>
      <div><dt>Since</dt><dd>${escapeHtml(model.sinceLabel)}</dd></div>
      <div><dt>Generated</dt><dd>${escapeHtml(shortDate(model.generatedAt))}</dd></div>
    </dl>
  </section>

  <section class="block">
    <div class="block-head"><h2>What changed</h2><span>${model.updates.length} item${model.updates.length === 1 ? "" : "s"}</span></div>
    <div class="cards">${model.updates.map(updateCard).join("") || emptyState("No new public updates since the last release.")}</div>
  </section>

  <section class="grid g2">
    <section class="block"><div class="block-head"><h2>Tech mentioned</h2><span>${model.tech.length}</span></div>${techList(model.tech)}</section>
    <section class="block"><div class="block-head"><h2>Release history</h2><span>${model.releases.length}</span></div>${releaseList(model.releases)}</section>
  </section>

  <footer>Generated by Chronicle / public allowlist only / ${escapeHtml(new Date(model.generatedAt).toLocaleString())}</footer>
</main>
</body>
</html>`;
}

export function buildPublicBuildModel(items, { version = "draft" } = {}) {
  const releases = getPublicReleases(items);
  const lastRelease = releases[0] ?? null;
  const publicItems = getSafePublicItems(items)
    .filter((item) => item.kind !== "release")
    .filter((item) => isAfterRelease(item, lastRelease))
    .sort(byDateDesc);
  const tech = countTags(publicItems.flatMap((item) => item.tech));

  return {
    generatedAt: new Date().toISOString(),
    version,
    lastRelease,
    sinceLabel: lastRelease?.data?.version && isPublishableText(lastRelease.data.version) ? `after ${lastRelease.data.version}` : "project start",
    headline: publicItems.length ? `${version}: ${publicItems[0].public_summary}` : `${version}: no new public updates yet`,
    story: buildStory(publicItems),
    updates: publicItems,
    releases,
    tech,
    skippedCount: items.filter((item) => item.visibility === "public").length - getSafePublicItems(items).length,
  };
}

export function getSafePublicItems(items) {
  return items
    .filter((item) => item.visibility === "public")
    .filter((item) => item.public_summary?.trim())
    .filter((item) => item.safety_flags?.length === 0)
    .filter((item) => isPublishableText(item.title) && isPublishableText(item.public_summary))
    .map((item) => ({ ...item, tech: safeTextList(item.tech) }));
}

function getPublicReleases(items) {
  return getSafePublicItems(items)
    .filter((item) => item.kind === "release" && item.data?.public_release === true)
    .sort((a, b) => String(b.created_at).localeCompare(String(a.created_at)) || byDateDesc(a, b));
}

function isAfterRelease(item, release) {
  if (!release) return true;
  const releasedIds = new Set(Array.isArray(release.data?.item_ids) ? release.data.item_ids : []);
  if (releasedIds.has(item.id)) return false;
  return String(item.updated_at ?? item.created_at ?? item.date) > String(release.data?.shipped_at ?? release.created_at ?? release.date);
}

function isPublishableText(value) {
  return scanTextForSafety(value, { includePrivacyPatterns: true }).length === 0;
}

function buildStory(items) {
  if (!items.length) {
    return "No public items have been approved for this release yet.";
  }
  const first = items[0].public_summary;
  const rest = items.length - 1;
  return rest > 0
    ? `${first} This update includes ${rest} more public change${rest === 1 ? "" : "s"}.`
    : first;
}

function updateCard(item) {
  return `<article class="card"><div class="top"><span class="badge">${escapeHtml(TYPE_LABELS[item.type] ?? item.kind)}</span><time>${escapeHtml(item.date)}</time></div><h3>${escapeHtml(item.public_summary)}</h3>${item.tech?.length ? `<div class="chips">${item.tech.slice(0, 5).map((tech) => `<span>${escapeHtml(tech)}</span>`).join("")}</div>` : ""}</article>`;
}

function techList(tech) {
  if (!tech.length) return emptyState("Tech tags will appear after public updates mention them.");
  return `<div class="chips big">${tech.map((item) => `<span>${escapeHtml(item.name)} / ${item.count}</span>`).join("")}</div>`;
}

function releaseList(releases) {
  if (!releases.length) return emptyState("No shipped public releases recorded yet.");
  return `<ol class="releases">${releases.slice(0, 8).map((item) => `<li><strong>${escapeHtml(releaseLabel(item))}</strong><span>${escapeHtml(item.public_summary)}</span></li>`).join("")}</ol>`;
}

function releaseLabel(item) {
  const version = item.data?.version;
  if (typeof version === "string" && version.trim() && isPublishableText(version)) {
    return version;
  }
  return item.title;
}

function safeTextList(values) {
  return Array.isArray(values) ? values.filter((value) => typeof value === "string" && isPublishableText(value)) : [];
}

function emptyState(text) {
  return `<div class="empty">${escapeHtml(text)}</div>`;
}

function countTags(tags) {
  const counts = new Map();
  for (const tag of tags.filter(Boolean)) counts.set(tag, (counts.get(tag) ?? 0) + 1);
  return Array.from(counts.entries()).sort((a, b) => b[1] - a[1]).map(([name, count]) => ({ name, count }));
}

function shortDate(value) {
  return value ? new Date(value).toLocaleDateString() : "unknown";
}

function byDateDesc(a, b) {
  return String(b.date).localeCompare(String(a.date)) || String(b.created_at).localeCompare(String(a.created_at));
}

const CSS = `
:root{--bg:#f6f3ec;--surface:#fffdf8;--surface-2:#ede7da;--ink:#181713;--muted:#6f6759;--line:#ddd4c4;--accent:#246b66;--accent-2:#9b5a2e;--shadow:0 18px 48px -36px rgba(24,23,19,.55);--radius:8px;--max:1080px}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:16px;line-height:1.55}.shell{max-width:var(--max);margin:0 auto;padding:44px 22px 60px}.hero{padding:26px 0 18px}.eyebrow{margin:0 0 10px;color:var(--accent);font:800 12px/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.14em;text-transform:uppercase}h1,h2,h3,p{margin-top:0}h1{font-size:clamp(40px,8vw,78px);line-height:.92;letter-spacing:0;margin-bottom:14px}.lede{max-width:58ch;color:var(--muted);font-size:18px}.release-card{display:grid;grid-template-columns:1fr 330px;gap:22px;align-items:stretch;background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:22px;margin:16px 0 20px}.label{display:block;color:var(--accent-2);font:800 11px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px}.release-card h2{font-size:28px;line-height:1.1;margin-bottom:10px}.release-card p{color:var(--muted);margin:0}.release-card dl{margin:0;display:grid;gap:8px}.release-card dl div{border:1px solid var(--line);border-radius:var(--radius);padding:12px}.release-card dt{color:var(--muted);font:750 11px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;text-transform:uppercase;letter-spacing:.06em}.release-card dd{margin:4px 0 0;font-size:20px;font-weight:850}.block{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:20px;margin-top:16px}.block-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.block-head h2{font-size:22px;margin:0}.block-head span{color:var(--muted);font:750 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.card{border:1px solid var(--line);border-radius:var(--radius);padding:16px;background:#fff}.top{display:flex;align-items:center;gap:8px;margin-bottom:12px}.badge{background:var(--surface-2);border-radius:7px;color:var(--accent);font:850 10px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.05em;text-transform:uppercase;padding:5px 8px}time{margin-left:auto;color:var(--muted);font:650 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.card h3{font-size:17px;line-height:1.28;margin-bottom:12px}.chips{display:flex;gap:7px;flex-wrap:wrap}.chips span{border:1px solid var(--line);border-radius:999px;padding:4px 9px;color:var(--muted);font:700 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.chips.big span{font-size:13px;color:var(--ink)}.grid{display:grid;gap:16px}.g2{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}.empty{border:1px dashed var(--line);border-radius:var(--radius);padding:16px;color:var(--muted)}.releases{margin:0;padding-left:20px;display:grid;gap:10px}.releases li span{display:block;color:var(--muted);font-size:14px}footer{border-top:1px solid var(--line);margin-top:28px;padding-top:18px;text-align:center;color:var(--muted);font:650 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}@media(max-width:860px){.release-card,.g2{grid-template-columns:1fr}.cards{grid-template-columns:1fr 1fr}}@media(max-width:560px){.shell{padding:28px 14px 44px}.cards{grid-template-columns:1fr}.release-card{padding:16px}h1{font-size:42px}.release-card h2{font-size:23px}}
`;
