import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadChronicleStore } from "../store/eventsStore.js";
import { escapeHtml } from "../utils/html.js";

const STATUS_LABELS = {
  completed: "shipped",
  in_progress: "in progress",
  planned: "planned",
  idea: "idea",
  blocked: "blocked",
  unknown: "unknown",
};

const TYPE_LABELS = {
  feature_added: "feature",
  bugfix: "bugfix",
  refactor: "refactor",
  dependency_changed: "dependency",
  version_bump: "version",
  decision: "decision",
  note: "note",
};

export async function renderTeamReportToFile({ storePath, outputPath }) {
  const store = await loadChronicleStore(storePath);
  const html = renderTeamReport(store.items, { storePath });
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, html, "utf8");
  return { outputPath, itemCount: store.items.length, visibleCount: getReportItems(store.items).length };
}

export function renderTeamReport(items, { storePath = "data/chronicle.json" } = {}) {
  const reportItems = getReportItems(items);
  const model = buildTeamReportModel(reportItems);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Chronicle - Team Report</title>
<style>${CSS}</style>
</head>
<body>
<main class="shell">
  <header class="hero">
    <div>
      <p class="eyebrow">Team report · ${escapeHtml(shortDate(model.generatedAt))}</p>
      <h1>Chronicle Team Report</h1>
      <p class="lede">A shareable status view built from explicitly team/public Chronicle items. Private notes, raw transcript text, and file paths are not rendered.</p>
    </div>
    <section class="share-note" aria-label="Safety note">
      <strong>Filtered view</strong>
      <span>Source: ${escapeHtml(storePath)}</span>
      <span>${model.visibleCount} visible item${model.visibleCount === 1 ? "" : "s"}</span>
    </section>
  </header>

  <section class="stats" aria-label="Report stats">
    ${stat(model.shipped.length, "shipped")}
    ${stat(model.inProgress.length, "in progress")}
    ${stat(model.blocked.length, "blocked")}
    ${stat(model.decisions.length, "decisions")}
    ${stat(model.activity.length, "timeline items")}
    ${stat(model.timeLabel, "time spent")}
  </section>

  ${emptyNotice(model)}

  <section class="grid g2">
    ${reportSection("What Shipped", model.shipped, "completed")}
    ${reportSection("In Progress", model.inProgress, "in_progress")}
  </section>

  <section class="grid g2">
    ${reportSection("Blocked", model.blocked, "blocked")}
    ${decisionSection(model.decisions)}
  </section>

  <section class="block">
    <div class="block-head"><h2>Recent Timeline</h2><span>${model.activity.length} item${model.activity.length === 1 ? "" : "s"}</span></div>
    <div class="timeline">${timelineItems(model.activity)}</div>
  </section>

  <footer>Generated by Chronicle · team-safe filtered report · ${escapeHtml(new Date(model.generatedAt).toLocaleString())}</footer>
</main>
</body>
</html>`;
}

function getReportItems(items) {
  return items
    .filter((item) => item.visibility === "team" || item.visibility === "public")
    .map(toReportItem)
    .sort(byDateDesc);
}

function toReportItem(item) {
  const summary = item.visibility === "public"
    ? item.public_summary
    : item.summary;

  return {
    id: item.id,
    kind: item.kind,
    type: item.type,
    title: item.title,
    summary: oneLine(summary || item.title),
    date: item.date,
    source_tool: item.source_tool,
    tech: item.tech ?? [],
    status: item.status ?? "unknown",
    visibility: item.visibility,
    timeMinutes: getTimeMinutes(item),
  };
}

function buildTeamReportModel(items) {
  const decisions = items.filter(isDecision);
  const shipped = items.filter((item) => item.status === "completed" && !isDecision(item));
  const inProgress = items.filter((item) => item.status === "in_progress" && !isDecision(item));
  const blocked = items.filter((item) => item.status === "blocked" && !isDecision(item));
  const totalMinutes = items.reduce((total, item) => total + item.timeMinutes, 0);

  return {
    generatedAt: new Date().toISOString(),
    visibleCount: items.length,
    shipped,
    inProgress,
    blocked,
    decisions,
    activity: items.slice(0, 12),
    timeLabel: totalMinutes > 0 ? formatMinutes(totalMinutes) : "not captured",
  };
}

function reportSection(title, items, status) {
  return `<section class="block"><div class="block-head"><h2>${escapeHtml(title)}</h2><span>${items.length}</span></div><div class="stack">${items.map((item) => itemCard(item, status)).join("") || emptyState("No items in this group.")}</div></section>`;
}

function decisionSection(items) {
  return `<section class="block"><div class="block-head"><h2>Decisions</h2><span>${items.length}</span></div><div class="stack">${items.map((item) => itemCard(item, "decision")).join("") || emptyState("No team-visible decisions yet.")}</div></section>`;
}

function itemCard(item, status = item.status) {
  const badgeLabel = status === "decision" ? "decision" : STATUS_LABELS[item.status] ?? TYPE_LABELS[item.type] ?? item.kind;
  return `<article class="card item"><div class="top"><span class="badge st-${escapeHtml(status)}">${escapeHtml(badgeLabel)}</span><span class="date">${escapeHtml(item.date)}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p>${meta(item)}</article>`;
}

function timelineItems(items) {
  return items.map((item) => `<article class="row"><div><time>${escapeHtml(item.date)}</time><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p></div><div class="row-meta"><span class="badge st-${escapeHtml(item.status)}">${escapeHtml(STATUS_LABELS[item.status] ?? item.status)}</span>${item.source_tool ? `<span>${escapeHtml(item.source_tool)}</span>` : ""}</div></article>`).join("") || emptyState("No team-visible timeline items yet.");
}

function meta(item) {
  const parts = [
    item.source_tool,
    item.visibility,
    item.timeMinutes > 0 ? formatMinutes(item.timeMinutes) : null,
  ].filter(Boolean);
  const tech = item.tech.slice(0, 4);
  return `<div class="meta">${parts.map((part) => `<span>${escapeHtml(part)}</span>`).join("")}${tech.map((part) => `<span>${escapeHtml(part)}</span>`).join("")}</div>`;
}

function stat(value, label) {
  return `<div class="stat"><strong>${escapeHtml(value)}</strong><span>${escapeHtml(label)}</span></div>`;
}

function emptyNotice(model) {
  if (model.visibleCount > 0) return "";
  return `<section class="notice"><strong>No team-visible items yet.</strong><span>No Chronicle items are marked team or public yet.</span></section>`;
}

function emptyState(text) {
  return `<div class="empty">${escapeHtml(text)}</div>`;
}

function getTimeMinutes(item) {
  const value = item.data?.time_spent_minutes ?? item.data?.duration_minutes ?? item.data?.elapsed_minutes;
  return Number.isFinite(value) && value > 0 ? value : 0;
}

function isDecision(item) {
  return item.kind === "decision" || item.type === "decision";
}

function formatMinutes(minutes) {
  if (minutes < 60) return `${minutes}m`;
  const hours = Math.floor(minutes / 60);
  const remainder = minutes % 60;
  return remainder ? `${hours}h ${remainder}m` : `${hours}h`;
}

function oneLine(value) {
  return String(value ?? "").replace(/\s+/g, " ").trim().slice(0, 240);
}

function shortDate(value) {
  return value ? new Date(value).toLocaleDateString() : "unknown";
}

function byDateDesc(a, b) {
  return String(b.date).localeCompare(String(a.date)) || String(b.id).localeCompare(String(a.id));
}

const CSS = `
:root{--bg:#f7f8f5;--surface:#fff;--surface-2:#eef2f0;--ink:#17201c;--muted:#66736d;--line:#d9e0dc;--accent:#235b78;--green:#287a4d;--amber:#9a6b1b;--red:#b4423c;--violet:#684ea0;--shadow:0 18px 42px -34px rgba(23,32,28,.55);--radius:8px;--max:1120px}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:16px;line-height:1.55}.shell{max-width:var(--max);margin:0 auto;padding:36px 22px 56px}.hero{display:grid;grid-template-columns:1fr 310px;gap:22px;align-items:end;padding:24px 0 22px;border-bottom:1px solid var(--line)}.eyebrow{margin:0 0 9px;color:var(--accent);font:750 12px/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.13em;text-transform:uppercase}h1,h2,h3,p{margin-top:0}h1{font-size:clamp(34px,6vw,62px);line-height:.96;letter-spacing:0;margin-bottom:12px}h2{font-size:22px;margin:0}.lede{max-width:66ch;color:var(--muted);font-size:17px;margin:0;overflow-wrap:anywhere}.share-note{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:16px;box-shadow:var(--shadow);display:grid;gap:5px}.share-note span{color:var(--muted);font-size:13px}.stats{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin:20px 0}.stat,.card,.block,.notice{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow)}.stat{padding:15px;min-width:0}.stat strong{display:block;font-size:26px;line-height:1;overflow-wrap:anywhere}.stat span{display:block;margin-top:7px;color:var(--muted);font:700 11px/1.2 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.04em;text-transform:uppercase}.grid{display:grid;gap:14px;margin-top:14px}.g2{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}.block{padding:18px}.block-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px}.block-head span{color:var(--muted);font:700 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.stack{display:grid;gap:10px}.card{padding:15px;box-shadow:none}.item .top{display:flex;align-items:center;gap:10px;margin-bottom:8px}.date{margin-left:auto;color:var(--muted);font:600 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.badge{font:800 10px/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.05em;text-transform:uppercase;border-radius:7px;padding:5px 8px;background:var(--surface-2);color:var(--muted)}.st-completed{background:#e8f4ee;color:var(--green)}.st-in_progress{background:#fff4dd;color:var(--amber)}.st-blocked{background:#fae9e8;color:var(--red)}.st-decision{background:#f0ecfa;color:var(--violet)}.st-planned,.st-idea,.st-unknown{background:var(--surface-2);color:var(--muted)}.item h3,.row h3{font-size:16px;line-height:1.25;margin:0 0 7px}.item p,.row p{color:var(--muted);font-size:14px;margin:0}.meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.meta span,.row-meta span{border:1px solid var(--line);border-radius:999px;padding:3px 8px;color:var(--muted);font:650 11px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.timeline{display:grid;gap:10px}.row{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:start;padding:14px 0;border-top:1px solid var(--line)}.row:first-child{border-top:0}.row time{display:block;color:var(--accent);font:750 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;margin-bottom:5px}.row-meta{display:flex;gap:6px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.empty{border:1px dashed var(--line);border-radius:var(--radius);padding:16px;color:var(--muted)}.notice{padding:16px;margin-bottom:14px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.notice span{color:var(--muted);overflow-wrap:anywhere}code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:var(--surface-2);border-radius:5px;padding:1px 4px;overflow-wrap:anywhere}footer{border-top:1px solid var(--line);margin-top:28px;padding-top:18px;color:var(--muted);text-align:center;font:600 12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}@media(max-width:900px){.hero,.g2{grid-template-columns:1fr}.stats{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:560px){.shell{padding:22px 14px 42px}.stats{grid-template-columns:1fr}.row{grid-template-columns:1fr}.row-meta{justify-content:flex-start}.share-note{padding:14px}}
`;
